schtasks /delete /tn "\ARGO2_Watchdog_XAG" /f
schtasks /delete /tn "\ARGO2_Train_XAG" /f
schtasks /delete /tn "\Argo2_XAG_Training" /f
schtasks /delete /tn "\Argo2_XAG_BG" /f
schtasks /delete /tn "\Argo2_XAG_BG_NoIT" /f
schtasks /delete /tn "\Argo2_XAG_Training_Dung5" /f
schtasks /delete /tn "\Argo2_XAG_Training_Dungla" /f
schtasks /delete /tn "\Argo2_XAG_V6" /f
schtasks /delete /tn "\ArgoTraining" /f
schtasks /delete /tn "\RunArgo2XAG" /f
